### ISSUE TITLE
recipe structure?

### ISSUE THREAD

**Issue by yeungs** [limadelic/teamcity#1]
Hi Isel, I was able download this cookbook and tweak it a little bit to get it to work. You did most of the work. :) 

I would like to contribute back your code. I noticed the structure and name on GitHub isn't consistent and easy for someone to search for TeamCity. Should "https://github.com/limadelic/cookbooks" be "https://github.com/limadelic/teamcitywindows" ? When I tried to create a fork it only allowed me to fork from cookbooks level.

**Comment by isel** [comment]
You are right, cookbooks is not easy to search. I will change it to just teamcity, because the recipe already says agent windows install. That way we could add recipes for ubuntu.
And yes, it would be awesome if you contribute. Very very happy it was useful for you.

**Comment by isel** [comment]
Hi Yeung, i renamed the repo. Please let me know if it looks better.

Thank you very much!

Isel

**Comment by yeungs** [comment]
Thank you isel. I will try to upload my changes by the end of 2015-Apr-09
